# @package __global__

classifier_free_guidance:
  training_dropout: 0.0 # Substituted by attribute_dropout
  inference_coef: 3.0

attribute_dropout:
  args:
    active_on_eval: false
  text:
    description: 0.3
  video:
    video: 0.3

fuser:
  cross_attention_pos_emb: false
  cross_attention_pos_emb_scale: 1
  sum: []
  prepend: []
  cross_sum: [] # Sum both and send to cross att
  cat_att_cross: [description, video] # Cat, perform self-att between cated conditioners, send to cross att
  cross: []
  input_interpolate: []

conditioners:
  description:
    model: t5
    t5:
      name: t5-base
      finetune: true
      word_dropout: 0.3
      normalize_text: false
  video:
    model: video_4_text
    video_4_text:
      name: google/vivit-b-16x2-kinetics400
      video_len: 32
      finetune: false
      num_hidden_layers: 12
      num_attention_heads: 12
      kernel_size: 2